# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install -g @aws-amplify/cli
      - name: Retrieve Secret and setup amplify
        env:
          ACCESSKEYID: ${{secrets.ACCESSKEYID}}
          SECRETACCESSKEY: ${{secrets.SECRETACESSKEY}}
        run: bash -xuv setupscript.sh
      - run: npm install
      - name: Running Build test
        env:
          GENERATE_SOURCEMAP: false
        run: npm run build --if-present

      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # - name: Test with pytest
      #   env:
      #     API_KEY: ${{secrets.API_KEY_DB}}
      #   run: |
      #     if [ -f Testcase.py ]; then python Testcase.py; fi
